# Generated by Django 5.1.4 on 2024-12-10 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_material_supplier_materialsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='validDay',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
