# Generated by Django 5.1.4 on 2024-12-10 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_ingredient_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='materialID',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='materialsource',
            name='materialID',
        ),
        migrations.RemoveField(
            model_name='materialsource',
            name='supplierID',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientMaterial', to='functions.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientProduct', to='functions.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialsource',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sourceMaterial', to='functions.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialsource',
            name='supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sourceSupplier', to='functions.supplier'),
            preserve_default=False,
        ),
    ]
