# Generated by Django 5.1.4 on 2024-12-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0005_remove_ingredient_materialid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
