# Generated by Django 5.1.4 on 2024-12-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0007_alter_materialsource_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsource',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceMaterial', to='functions.material'),
        ),
        migrations.AlterField(
            model_name='materialsource',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceSupplier', to='functions.supplier'),
        ),
    ]
