# Generated by Django 5.1.4 on 2024-12-13 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0008_alter_materialsource_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='shipDay',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
