# Generated by Django 5.1.4 on 2024-12-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0011_customer_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='importDate',
            field=models.DateField(),
        ),
    ]
