# Generated by Django 5.1.4 on 2024-12-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0013_refreshrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rfmScore',
            field=models.CharField(blank=True, default='000', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.CharField(blank=True, default='未分類', max_length=50, null=True),
        ),
    ]
