# Generated by Django 5.1.4 on 2024-12-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0016_order_stored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='importAmount',
            field=models.IntegerField(null=True),
        ),
    ]
